events/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import AllPostsListView, EventCreateView, EventUpdateView, EventDeleteView, ProfileDetailView, ProfileListView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),

    path('all-events/', views.all_events, name="all-events"),
    path('saved-events/', views.saved_events, name="saved-events"),
    path('discover/', views.discover, name="discover"), 

    path('new-event/', EventCreateView.as_view(), name="new-event"),
    path('posts/<int:pk>/update/', EventUpdateView.as_view(), name="update-event"),
    path('posts/<int:pk>/delete/', EventDeleteView.as_view(), name="delete-event"),
    path('posts/<int:pk>/', views.individual_event, name="individual-event"),

    path('posts/<int:pk>/favorite/', views.favorite, name='fav-event'),
    path('posts/<int:pk>/unfavorite/', views.unfavorite, name='unfav-event'),
    path('posts/<int:pk>/rsvp/', views.rsvp, name='rsvp-event'),
    path('posts/<int:pk>/unrsvp/', views.unrsvp, name='unrsvp-event'),

    path('profile/<slug:slug>/', ProfileDetailView.as_view(), name="profile"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finder/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

protest_finder/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from django import forms
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.utils.text import slugify
from django.shortcuts import reverse

class Event(models.Model):
    event_organizer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    event_name = models.CharField(max_length = 128)
    event_description = models.TextField(max_length = 2048, null=True, blank=True)
    event_date = models.DateField(null=True, blank=True)
    event_time = models.TimeField(null=True, blank=True)
    event_banner = models.ImageField(null=True, blank=True)
    event_tags = models.CharField(null=True, blank=True, max_length = 512)
    
    date_posted = models.DateTimeField(auto_now_add=True)
    
    event_address = models.CharField(max_length=256, null=True, blank=True)
    event_latitude = models.CharField(max_length=32, null=True, blank=True)
    event_longitude = models.CharField(max_length=32, null=True, blank=True)

    @property
    def get_username(self):
        return self.event_organizer.username

    def get_absolute_url(self): 
        return reverse('events:all-events')

    def __str__(self):
        return self.event_name 
    
    def as_dict(self):
        return {
                "event_name": self.event_name,
                "event_latitude": self.event_latitude,
                "event_longitude": self.event_longitude,
                "event_url": self.get_absolute_url(),
                "pk": self.pk
            }

    def as_dict(self):
        return {
                "event_name": self.event_name,
                "event_latitude": self.event_latitude,
                "event_longitude": self.event_longitude,
                "event_url": self.get_absolute_url(),
                "pk": self.pk
                }

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="default_pfp.png", upload_to="profile_pics")
    slug = models.SlugField(unique=False, null=True)
    favorites = models.ManyToManyField(Event, related_name='favorited_by')
    rsvped = models.ManyToManyField(Event, related_name='rsvped_by')
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
       return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

events/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Event


class CreateUserForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class NewEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'event_description', 'event_date', 'event_time', 'event_address', 
        'event_latitude', 'event_longitude', 'event_banner', 'event_tags']

events/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .filters import EventFilter
from .forms import CreateUserForm, NewEventForm
from .models import Event, Profile
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.http import JsonResponse
import json
import datetime

def index(request):
    if request.user.is_authenticated:
        return redirect('events:home')
    else:
        form = CreateUserForm()
        if request.method == "POST" and "signup" in request.POST:
            form = CreateUserForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                form.save()
                messages.success(request, "Account created!")
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                return redirect('events:home')
            else:
                context = {'reg_error': 'Invalid request. Try again!'}
                return render(request, 'events/index.html', context)
        
        elif (request.method == "POST") and ("signin" in request.POST):
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request, 'events/home.html')
            else:
                context = {'login_error':'Invalid username and/or password.'}
                return render(request, 'events/index.html', context)
        else: 
            return render(request, 'events/index.html')

def home(request):
    now = datetime.date.today()
    all_events_qs = Event.objects.filter(event_date__gte=now).order_by('event_date')
    all_events = []
    for x in all_events_qs:
        if x.event_latitude and x.event_longitude:
            all_events.append(x.as_dict())
    context = {'all_events': all_events}
    return render(request, 'events/home.html', context)

def signin(request):
    if (request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'events/home.html')
        else:
            context = {'login_error':'Invalid username and/or password.'}
            return render(request, 'events/signin.html', context)
    else: 
        return render(request, 'events/signin.html')

def signup(request):
    if request.user.is_authenticated:
        return redirect('events:home')
    else:
        form = CreateUserForm()
        if request.method == "POST" :
            form = CreateUserForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                form.save()
                messages.success(request, "Account created!")
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                return redirect('events:home')
        return render(request, 'events/signup.html')


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    fields = ['event_name', 'event_description', 'event_date', 'event_time', 'event_address', 
        'event_latitude', 'event_longitude', 'event_banner', 'event_tags']
    template_name = 'events/new-event.html'

    def form_valid(self, form):
        form.instance.event_organizer = self.request.user
        return super().form_valid(form)

class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    fields = ['event_name', 'event_description', 'event_date', 'event_time', 'event_address', 
        'event_latitude', 'event_longitude', 'event_banner', 'event_tags']
    template_name = 'events/update-event.html'
    context_object_name = 'post'

    def form_valid(self, form):
        form.instance.event_organizer = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        event = self.get_object()
        if self.request.user == event.event_organizer:
            return True
        return False

class EventDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Event
    template_name = 'events/delete-event.html'
    context_object_name = 'post'

    success_url = '/'

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.event_organizer:
            return True
        return False

def signout(request):
    logout(request)
    return redirect('events:home')

def all_events(request):
    latest_events = Event.objects.order_by('-date_posted')
    myFilter = EventFilter(request.GET, queryset=latest_events)
    filtered_events = myFilter.qs
    
    pager = Paginator(filtered_events, 5)
    page_number = request.GET.get('page')
    page_setting = pager.get_page(page_number)

    context = {'events':page_setting, 'eventFilter':myFilter}
    return render(request, 'events/all-events.html', context)

def discover(request):
    now = datetime.date.today()
    new_events = Event.objects.filter(event_date__gte=now).order_by('-date_posted')[:3]
    upcoming = Event.objects.filter(event_date__gte=now).order_by('event_date')[:3]
    context = {'new_events':new_events, 'upcoming':upcoming}
    return render(request, 'events/discover.html', context)

@login_required
def saved_events(request):
    now = datetime.date.today()
    saved = (request.user.profile.favorites.filter(event_date__gte=now) | request.user.profile.rsvped.filter(event_date__gte=now)).distinct()
    myFilter = EventFilter(request.GET, queryset=saved)
    saved = myFilter.qs

    favs = request.user.profile.favorites.all()
    rsvped = request.user.profile.rsvped.all()

    context = {'events':saved, 'eventFilter':myFilter, 'favorited_posts':favs, 'rsvped_posts':rsvped}
    return render(request, 'events/saved-events.html', context)

@login_required
def favorite(request, pk): 
    post = Event.objects.get(pk=pk)
    request.user.profile.favorites.add(post)
    return HttpResponseRedirect(reverse('events:individual-event', args=(pk,)))

@login_required
def unfavorite(request, pk): 
    post = Event.objects.get(pk=pk)
    request.user.profile.favorites.remove(post)
    return HttpResponseRedirect(reverse('events:individual-event', args=(pk,)))

@login_required
def rsvp(request, pk): 
    post = Event.objects.get(pk=pk)
    request.user.profile.rsvped.add(post)
    return HttpResponseRedirect(reverse('events:individual-event', args=(pk,)))

@login_required
def unrsvp(request, pk): 
    post = Event.objects.get(pk=pk)
    request.user.profile.rsvped.remove(post)
    return HttpResponseRedirect(reverse('events:individual-event', args=(pk,)))

class AllPostsListView(ListView):
    model = Event
    template_name = 'events/all-events.html'
    context_object_name = 'events'
    ordering = ['date_posted']    

def individual_event(request, pk):
    post = Event.objects.get(pk=pk)
    if request.user.is_authenticated:
        favs = request.user.profile.favorites.all()
        rsvped = request.user.profile.rsvped.all()
        context = {'favorite_posts':favs, "rsvped_posts":rsvped, 'post':post}
        return render(request, 'events/individual-event.html', context)
    else:
        context = {'post':post}
        return render(request, 'events/individual-event.html', context)

@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'events/profile.html'
    slug_url_kwarg = "slug"
    context_object_name = 'profile'
    
class ProfileListView(ListView):
    model = Profile
    template_name = 'events/people.html'
    context_object_name = 'profiles'
    ordering = ['user.username']

events/templates/events/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'events/main.css' %}">

    <title>Finder</title>
  </head>
  <body>

    

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'events:index' %}">Finder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Discover</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:saved-events' %}">Calendar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:all-events' %}">All Events</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %} 
            <a href="{% url 'events:signout' %}">Sign out</a>&nbsp;&nbsp;
            <a href="{% url 'events:profile' slug=user.username %}">Profile</a>
            {% else %}
            <a href="{% url 'events:signup' %}">Sign up</a>&nbsp;&nbsp;
            <a href="{% url 'events:signin' %}">Sign in</a>
            {% endif %}
            <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
          </form>
        </div>
    </nav>
    <br>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            {% block sidebar %}{% endblock %}
          </div>
        </div>
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

events/templates/events/base2.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'events/main.css' %}">

    <title>Finder</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: white; padding: 15px;">
        <a class="navbar-brand" href="{% url 'events:index' %}"><img src="{% static 'events/images/logo.png' %}" width=200px style="margin-right: 120px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:discover' %}">Discover</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:saved-events' %}">Calendar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:all-events' %}">All Events</a>
            </li>
          </ul>

          <ul class="navbar-nav">
          {% if user.is_authenticated %} 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:signout' %}">Sign out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:profile' slug=user.username %}">Profile</a>
          </li>
          
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:signup' %}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:signin' %}">Sign in</a>
          </li>
          {% endif %}
        </ul>
        </div>
    </nav>
    <br>

    <style type="text/css">
      html,
      body {
        overflow-x: hidden;
      }
  
      .navbar-light .navbar-brand {
          color: #F7C547;
      }
      
      .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.show, .navbar-light .navbar-nav .show>.nav-link {
          color: #414141;
          text-transform: uppercase;
      }
      
      .navbar-light .navbar-nav .nav-link {
          color: #414141;
          text-transform: uppercase;
          font-weight: 700;
          padding: 0px 25px;
          font-size: 16;
      }
      
      .navbar-light .navbar-nav .nav-link:focus, .navbar-light .navbar-nav .nav-link:hover {
          color: #F7C547 !important;
      }
  </style>

    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

events/templates/events/individual-event.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}

<div class="event-container">
{% if post.banner %} 
<img style="border-radius: 25px" href="{{ post.banner.url }}" alt="{{ post.event_name }}" width="100%" height="200px">
{% endif %}

<div class="flex-row" style='align-items: center;'>
    <h1>{{ post.event_name }}.</h1>
    {% if post.event_organizer == user %}
    <div>
        <a href="{% url 'events:update-event' post.id %}"><button class="save btn btn-outline-light">Edit Post.</button></a>
        <a  href="{% url 'events:delete-event' post.id %}"><button class="save btn btn-outline-light">Delete Post.</button></a>
        
    </div>
    {% endif %}
</div>


<div class="event-list">
    <div style="text-align: left;">
        {{ post.event_description }}
    </div>
</div>

{% if post.event_tags %}
<div class="event-list">
    <div style="text-align: left;">
        Tags: {{ post.event_tags }}
    </div>
</div>
{% endif %}

</div>

<script language="javascript">
    function copyToClipboard() {
        var copyText = document.getElementById("toCopy")
        copyText.type = 'text';
        copyText.select();
        document.execCommand("copy");
        copyText.type = 'hidden';
        alert("Copied the text: " + copyText.value);
    }
</script>

{% endblock %}

{% block sidebar %}
<div>
    <div class="icons">
        <div class="icons">
            {% if post in favorite_posts %}
            <form method="post" action="{% url 'events:unfav-event' post.id %}">
                {% csrf_token %}
                <input type="image" onclick='changeFav()' src="https://i.imgur.com/pw5U3Vy.png" style="width: 25px;margin-right: 7px; filter:invert(100%)">
            </form>
            {% else %}
            <form action="{% url 'events:fav-event' post.id %}">
                {% csrf_token %}
                <input type="image" onclick='changeFav()' src="https://i.imgur.com/kDDHION.png" style="width: 25px;margin-right: 7px; filter:invert(100%)">
            </form>
            {% endif %}
        <em>fave.</em>
        </div>
        
        <div class="icons">
            {% if post in rsvped_posts %}
            <form method="post" action="{% url 'events:unrsvp-event' post.id %}">
                {% csrf_token %}
                <input type="image" onclick='changeRSVP()' src="https://i.imgur.com/LyENq6z.png" style="width: 25px;margin-right: 7px; filter:invert(100%)">
            </form>
            {% else %}
            <form method="post" action="{% url 'events:rsvp-event' post.id %}">
                {% csrf_token %}
                <input type="image" onclick='changeRSVP()' src="https://i.imgur.com/UUP1FbJ.png" style="width: 25px; margin-right: 7px; filter:invert(100%)">
            </form>
            {% endif %}
            <em>rsvp.</em>
        </div>
        
        <div class="icons">
            <input type="hidden" value="{{ request.build_absolute_uri }}" id="toCopy">
            <input type="image" onclick="copyToClipboard()" style="width: 25px; align-self: start; margin-right:7px; filter:invert(100%)" src="https://i.imgur.com/My5FbZN.png">
            <em>share.</em>
        </div>
    </div>
    <div class="flex-col">
        {{ post.event_date|date:"l, F d, Y"  }} 
        {% if post.event_time %} <br>
            {{ post.event_time }}<br>
        {% endif %}
        {% if post.event_address %}
            <br>
            {{ post.event_address }}
            <br>
        {% endif %}
        
        {% if post.event_organizer.profile.profile_pic %}
        <br>
        <div>
            <a href="{% url 'events:profile' post.event_organizer.username %}"><img width=150px style="justify-content: center;" src="{{ post.event_organizer.profile.profile_pic.url }}"></a>
        </div>
        {% endif %}
        {% if post.event_organizer %}
        <a href="{% url 'events:profile' post.event_organizer.username %}">{{ post.event_organizer }}</a>
        {% endif %} 

        {% if post.longitude %}
            ({{ post.latitude }}, {{ post.longitude }})
        {% endif %}

       
    </div>
</div>
{% endblock %}

events/templates/events/people.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}

<h1>People</h1>
<hr>
{% if profiles %}
{% for profile in profiles %}
    {% if profile.user.first_name and profile.user.last_name %}}
     <h3><a href="{% url 'events:profile' slug=profile.user %}">{{ profile.user.first_name }}</a></h3>
    {% endif %}
{% endfor %}
{% endif %}

{% endblock %}

events/templates/events/signin.html
{% extends 'events/base.html' %}
{% load socialaccount %}
{% block content %}

<h1>Sign In.</h1>
<form method="post">
    {% csrf_token %}
    <div style="margin-left: 25px">
    <div class="form-group">
        <label>Username.</label>
        <input name="username" id="username" class="form-control form-input" type="text" placeholder="jsmith" required>
    </div>

    <div class="form-group">
        <label>Password.</label>
        <input name="password1" id="password" class="form-control form-input" type="password" placeholder="********" required>
    </div>

    <div class="form-group">
        <button name="signup" type="submit" class="save btn btn-outline-light">sign in.</button>
    </div>
</form>

<hr>
<a style="color:#F7C547;" href="{% provider_login_url 'google' %}">Sign in with Google.</a>
<p>Need an account? <a href="{% url 'events:signup' %}" style="color:#F7C547;">Sign up!</a></p>
</div>
{% endblock %}

events/templates/events/signup.html
{% extends 'events/base.html' %}
{% load socialaccount %}
{% block content %}
<h1>Sign up.</h1>

<form method="post">
    {% csrf_token %}
    <div style="margin-left: 25px">
    <div class="form-group">
        <label>First Name.</label>
        <input name="first_name" class="form-control form-input" type="text" placeholder="john" required>
    </div>

    <div class="form-group">
        <label>Last Name.</label>
        <input name="last_name" class="form-control form-input" type="text" placeholder="smith" required>
    </div>

    <div class="form-group">
        <label>Email.</label>
        <input name="email" class="form-control form-input" type="text" placeholder="jsmith@company.com">
    </div>

    <div class="form-group">
        <label>Username.</label>
        <input name="username" id="username" class="form-control form-input" type="text" placeholder="jsmith" required>
    </div>

    <div class="form-group">
        <label>Password.</label>
        <input name="password1" id="password" class="form-control form-input" type="password" placeholder="********" required>
    </div>
    
    <div class="form-group">
        <label>Confirm Password.</label>
        <input name="password2" id="confirm_password" class="form-control form-input" type="password" placeholder="********" required>
    </div>
    
    <div class="form-group">
        <button name="signup" type="submit" class="save btn btn-outline-light">sign up.</button>
    </div>
    
  </form>

  <hr>
  <a style="color:#F7C547;" href="{% provider_login_url 'google' %}">Sign up with Google.</a>
  <p>Have an account? <a style="color:#F7C547;" href="{% url 'events:signin' %}">Sign in!</a></p>
</div>
{% endblock %}